name: Publish release

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: sutoj/piler
  TEST_TAG: test
  ARCH: amd64

jobs:
  publish:
    if: github.ref_name == 'master'

    runs-on:
      - self-hosted
      - X64

    steps:
      - uses: actions/checkout@v4

      - name: Set version tag
        id: generate-version
        run: |
          read -r VERSION < VERSION
          COMMIT_ID="$( git rev-parse --short HEAD )"
          IMAGE_TAG="${VERSION}-${COMMIT_ID}"
          echo "image tag: $IMAGE_TAG"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TEST_TAG }} ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        shell: bash
