name: Publish release

on:
  push:
    tags:
      - piler*

env:
  IMAGE_NAME: sutoj/piler
  TEST_TAG: test

permissions:
  contents: write

jobs:
  publish:

    runs-on:
      - self-hosted
      - X64

    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#*-}" \
              --generate-notes

